apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prod
namePrefix: prod-

patches:
  - path: patch-env.yml

replicas: 
  - name: mpos-service
    count: 3 