apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json  

resources:
  - ../../base

namespace: mpos

patches:
  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
       name: mpos-rollout
      spec:
        template:
          spec:
            containers:
              - name: mpos-container
                env:
                  - name: SPRING_PROFILES_ACTIVE
                    value: staging
  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
       name: mpos-rollout
      spec:
        replicas: 2
               